---
id: History
name: History
full: History tracking library
description: >-
  A library that provides a way to track changes on arbitrary pieces of data in
  Horde applications.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_History
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Db: ^2
      pear.horde.org/Horde_Exception: ^2
  optional:
    pear:
      pear.horde.org/Horde_HashTable: ^1
      pear.horde.org/Horde_Mongo: ^1
      pear.horde.org/Horde_Test: ^2.1
